name: stream-buddy

services:
  stream-buddy:
    pull_policy: build
    build:
      dockerfile: Dockerfile
    container_name: stream-buddy
    environment:
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
    env_file:
      - .env
