name: stream-buddy

services:
  stream-buddy:
    image: ghcr.io/jordybronowicki37/stream-buddy:latest
    container_name: stream-buddy
    environment:
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
    env_file:
      - .env
    volumes:
      - ./data:/app/data
