name: Bump tag version
on:
  workflow_call:
    inputs:
      default_bump:
        description: The default version bump
        required: false
        type: string
        default: patch
    outputs:
      tag:
        description: The new tag version
        value: ${{ jobs.bump-tag.outputs.tag }}
  workflow_dispatch:
    inputs:
      default_bump:
        description: The default version bump
        required: true
        type: choice
        default: patch
        options:
          - patch
          - minor
          - major

jobs:
  bump-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      tag: ${{ steps.tag.outputs.new_tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Bump version and push tag
        id: tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: ${{ inputs.default_bump }}
          WITH_V: true
