name: Build and Publish Docker Image

on:
  workflow_call:
    inputs:
      image_name:
        description: The image name
        required: false
        type: string
        default: stream-buddy
      version:
        description: The image version
        required: true
        type: string
  workflow_dispatch:
    inputs:
      image_name:
        description: The image name
        required: false
        type: string
        default: stream-buddy
      version:
        description: The image version
        required: true
        type: string

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image with Cache
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: |
            ghcr.io/${{ github.actor }}/${{ inputs.image_name }}:${{ inputs.version }}
            ghcr.io/${{ github.actor }}/${{ inputs.image_name }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
